// ESLint 9 flat config.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const prettierRecommended = require('eslint-plugin-prettier/recommended');

module.exports = defineConfig([
  expoConfig,
  prettierRecommended,
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'coverage/**',
      'android/**',
      'ios/**',
      // Generated by `npm run db:types`.
      'src/types/database.types.ts',
      // Generated by the Expo CLI on every start; not ours to format.
      'expo-env.d.ts',
      '.expo/types/**',
      // Deno runtime with its own toolchain; linted separately.
      'supabase/functions/**',
    ],
  },
  {
    // Rules valid for every file type.
    rules: {
      // Prefer the `@/` alias over deep relative paths.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../../*'],
              message: 'Use the "@/" path alias instead of deep relative imports.',
            },
          ],
        },
      ],

      // `console.log` left in shipped code can leak user data to device logs.
      // warn/error are permitted for genuine diagnostics.
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    // The `@typescript-eslint` plugin is only registered for TS files by
    // eslint-config-expo, so its rules must be scoped identically.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Allow the `_` prefix convention for intentionally-unused bindings.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    // Test files, test setup, and scripts may use dev-only conveniences.
    files: ['**/*.test.ts', '**/*.test.tsx', '**/__tests__/**', 'jest.setup.ts', 'scripts/**'],
    rules: {
      'no-console': 'off',
      // `jest.mock` factories are hoisted above imports, so mocks must use
      // `require` to be initialised in time.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
]);
