import type { Database as Generated, Json } from './database.types';

/**
 * The database type the app actually uses.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * `database.types.ts` is generated by `supabase gen types` and is never
 * hand-edited — an edit there would be silently undone by the next
 * regeneration. But regenerating requires the Supabase CLI pointed at a database
 * that already has the migration applied, which is not available in every
 * environment where this code is compiled.
 *
 * So the additions from
 * `20260917000001_user_gyms_workout_types_daily_challenges.sql` are declared here
 * and merged onto the generated type. Everything in the app imports `Database`
 * from THIS module, so exactly one file knows the difference.
 *
 * WHEN THE TYPES ARE NEXT REGENERATED
 * -----------------------------------
 * Run `npm run db:types`, then delete the `*Additions` interfaces, the three
 * function entries, and the merging below, leaving a plain re-export. Nothing
 * else has to change, because no other module imports `database.types` directly.
 */

/**
 * Collapses an intersection into a single object type.
 *
 * NOT COSMETIC — the client does not compile without it. `supabase-js` constrains
 * a schema with `Tables: Record<string, GenericTable>` and `Row: Record<string,
 * unknown>`. TypeScript grants an implicit index signature to an object type
 * alias but NOT to an intersection of them, so `Row & Additions` fails that
 * constraint, the whole schema stops matching `GenericSchema`, and every query
 * silently degrades to `never` — which surfaces as a hundred confusing
 * "Property 'x' does not exist on type 'never'" errors far from this file.
 * Re-mapping the keys produces a plain object type that does satisfy it.
 */
type Simplify<T> = { [K in keyof T]: T[K] };

type Public = Generated['public'];
type Tables = Public['Tables'];

/** Columns added to `public.gyms` for member-submitted gyms. */
interface GymAdditions {
  description: string | null;
  /**
   * Absolute http(s) link to a photo.
   *
   * A URL rather than an uploaded file: the project ships no storage bucket and
   * no image picker, and a link behaves identically on web, iOS, and Android.
   */
  image_url: string | null;
  created_by: string | null;
}

/** Columns added to `public.sessions` for workout types. */
interface SessionAdditions {
  /**
   * What the member chose to train, e.g. `['chest', 'triceps']`.
   *
   * Empty for sessions logged before workout types existed. Never null: the
   * column is NOT NULL with a `'{}'` default, so callers never have to
   * distinguish "no categories" from "unknown".
   */
  workout_categories: string[];
}

/** Columns added to `public.exercises` for custom-exercise notes. */
interface ExerciseAdditions {
  description: string | null;
}

/** A candidate returned by `find_similar_gyms`. */
export interface SimilarGymRow {
  id: string;
  name: string;
  address: string | null;
  latitude: number;
  longitude: number;
  distance_metres: number;
  /** One of `same_name`, `same_address`, `similar_name`, `very_close`. */
  match_reason: string;
  /**
   * True when the server considers this near-certainly the same gym and will
   * refuse the submission until the member confirms.
   */
  is_probable_duplicate: boolean;
}

type ExtendedTables = Simplify<
  Omit<Tables, 'gyms' | 'sessions' | 'exercises'> & {
    gyms: {
      Row: Simplify<Tables['gyms']['Row'] & GymAdditions>;
      Insert: Simplify<Tables['gyms']['Insert'] & Partial<GymAdditions>>;
      Update: Simplify<Tables['gyms']['Update'] & Partial<GymAdditions>>;
      Relationships: Tables['gyms']['Relationships'];
    };
    sessions: {
      Row: Simplify<Tables['sessions']['Row'] & SessionAdditions>;
      Insert: Simplify<Tables['sessions']['Insert'] & Partial<SessionAdditions>>;
      Update: Simplify<Tables['sessions']['Update'] & Partial<SessionAdditions>>;
      Relationships: Tables['sessions']['Relationships'];
    };
    exercises: {
      Row: Simplify<Tables['exercises']['Row'] & ExerciseAdditions>;
      Insert: Simplify<Tables['exercises']['Insert'] & Partial<ExerciseAdditions>>;
      Update: Simplify<Tables['exercises']['Update'] & Partial<ExerciseAdditions>>;
      Relationships: Tables['exercises']['Relationships'];
    };
  }
>;

type ExtendedFunctions = Simplify<
  Public['Functions'] & {
    create_user_gym: {
      Args: {
        p_address?: string;
        p_city?: string;
        p_confirm_possible_duplicate?: boolean;
        p_country_code?: string;
        p_description?: string;
        p_image_url?: string;
        p_latitude: number;
        p_longitude: number;
        p_name: string;
        p_website?: string;
      };
      Returns: string;
    };
    find_similar_gyms: {
      Args: {
        p_address?: string;
        p_latitude: number;
        p_limit?: number;
        p_longitude: number;
        p_name: string;
      };
      Returns: SimilarGymRow[];
    };
    normalise_place_name: {
      Args: { p_value: string };
      Returns: string;
    };
  }
>;

export type Database = Simplify<
  Omit<Generated, 'public'> & {
    public: Simplify<
      Omit<Public, 'Tables' | 'Functions'> & {
        Tables: ExtendedTables;
        Functions: ExtendedFunctions;
      }
    >;
  }
>;

export type { Json };
